name: GitHub - $(product) site $(version) build $(counter) - 

variables:
  major: 1
  minor: 0
  patch: 0
  version: $[format('{0}.{1}.{2}', variables['major'], variables['minor'], variables['patch'])]
  counter: $[counter(variables['version'], 0)]
  fullVersion: $[format('{0}{1}.{2}', variables['version'], variables['quality'], variables['counter'])]
  product: 'RND'
  saName: 'chr$(product)sa$(stage)we'

trigger: 
  branches:
   include:
     - master

pool:
  name: At Home

stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      name: At Home
    steps:
    - template: build.yml

- stage: Production
  jobs:
  - deployment: ReleasePRD
    displayName: 'Release PRD'
    variables:
      stage: 'PRD'
      hostName: 'www.rickneeft.dev'
    pool:
      name: At Home
    environment: 'PRD'
    strategy:
      runOnce:
        deploy:
          steps:
          - template: release.yml